
package nl.hu.iac.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "bmiServiceInterface", targetNamespace = "http://nl.hu.iac/bmiservice/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BmiServiceInterface {


    /**
     * 
     * @param request
     * @return
     *     returns nl.hu.iac.wsinterface.BmiResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "bmiResponse", targetNamespace = "http://nl.hu.iac/bmiservice/response", partName = "response")
    public BmiResponse calculateBmi(
        @WebParam(name = "bmiRequest", targetNamespace = "http://nl.hu.iac/bmiservice/request", partName = "request")
        BmiRequest request)
        throws Fault
    ;

}
