
package nl.hu.iac.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bmiServiceService", targetNamespace = "http://nl.hu.iac/bmiservice/", wsdlLocation = "file:/D:/Users/Kevin Veld/IdeaProjects/soapservice/src/main/webapp/WEB-INF/wsdl/bmiservice.wsdl")
public class BmiServiceService
    extends Service
{

    private final static URL BMISERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BMISERVICESERVICE_EXCEPTION;
    private final static QName BMISERVICESERVICE_QNAME = new QName("http://nl.hu.iac/bmiservice/", "bmiServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Users/Kevin Veld/IdeaProjects/soapservice/src/main/webapp/WEB-INF/wsdl/bmiservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BMISERVICESERVICE_WSDL_LOCATION = url;
        BMISERVICESERVICE_EXCEPTION = e;
    }

    public BmiServiceService() {
        super(__getWsdlLocation(), BMISERVICESERVICE_QNAME);
    }

    public BmiServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BMISERVICESERVICE_QNAME, features);
    }

    public BmiServiceService(URL wsdlLocation) {
        super(wsdlLocation, BMISERVICESERVICE_QNAME);
    }

    public BmiServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BMISERVICESERVICE_QNAME, features);
    }

    public BmiServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BmiServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BmiServiceInterface
     */
    @WebEndpoint(name = "WS-Port")
    public BmiServiceInterface getWSPort() {
        return super.getPort(new QName("http://nl.hu.iac/bmiservice/", "WS-Port"), BmiServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BmiServiceInterface
     */
    @WebEndpoint(name = "WS-Port")
    public BmiServiceInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nl.hu.iac/bmiservice/", "WS-Port"), BmiServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BMISERVICESERVICE_EXCEPTION!= null) {
            throw BMISERVICESERVICE_EXCEPTION;
        }
        return BMISERVICESERVICE_WSDL_LOCATION;
    }

}
